version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11



  pre_build:
    commands:
      - echo ============================pre-build================================
      - pwd
      - ls -al
      - aws s3 cp s3://p2-secret-files/hibernate.properties p2-backend/src/resources/hibernate.properties
      - pwd
      - ls -al
      #(use the next line if there's an application.properties file and change the name of the bucket)
      #- aws s3 cp s3://rev-secret-bucket/application.properties src/main/resources/application.properties
      - aws s3 rm "s3://p2-s3-bucket/*" --recursive
  build:
    commands:
      - echo ============================build================================
      - cd p2-backend
      - mvn package -q -DskipTests
      - cd ./..
      - cd p2-frontend
      - npm install
      - npm install -g @angular/cli
      - npm i --save @fortawesome/fontawesome-svg-core
      - ng build
      - pwd
      - ls -al
      - cd ./..
  post_build:
    commands:
      - echo ============================post-build================================
      - pwd
      - ls -al
      - cd p2-frontend/dist/front-end-testing
      - aws s3 cp "./" "s3://p2-s3-bucket/" --recursive
      - pwd
      - ls -al
      - cd ./../../..
      - pwd
      - ls -al
      - cd p2-backend
      - pwd
      - ls -al
      - mv ./target/p2-backend-0.0.1.war ./../ROOT.war
      - pwd
      - ls -al

artifacts:
  files:
    - ROOT.war
    - .ebextensions/*